# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='person_images'),
        ),
    ]
