# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20161120_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.png', upload_to='person_images'),
        ),
    ]
