# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20161120_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
