# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
